USE DbProje
CREATE TABLE BRANCHS (
	branchID INT PRIMARY KEY,
	branchName varchar(50) NOT NULL,
	branchAdress varchar(100) NOT NULL,
	branchCity varchar(50) NOT NULL,
	branchFax varchar(50) NOT NULL
);

CREATE TABLE ACCOUNTS (
	accountID INT PRIMARY KEY,
	costumerID INT UNIQUE,
	accountDateOfJoin Date NOT NULL
);

CREATE TABLE ACCOUNTTYPES (
	accountID INT PRIMARY KEY,
	accountType varchar(50) NOT NULL,
	CONSTRAINT FK_TYPESID FOREIGN KEY (accountID) REFERENCES ACCOUNTS(accountID)

);
CREATE TABLE SAVINGACCOUNTS (
	accountID INT PRIMARY KEY,
	CONSTRAINT FK_SAVINGID FOREIGN KEY (accountID) REFERENCES ACCOUNTS(accountID)
);
CREATE TABLE CHECHKACCOUNTS (
	accountID INT PRIMARY KEY,
	CONSTRAINT FK_CHECKID FOREIGN KEY (accountID) REFERENCES ACCOUNTS(accountID)
);
CREATE TABLE OTHERACCOUNTS (
	accountID INT PRIMARY KEY,
	CONSTRAINT FK_OTHERID FOREIGN KEY (accountID) REFERENCES ACCOUNTS(accountID)
);
CREATE TABLE STAFFS (
	staffID INT PRIMARY KEY,
	staffName varchar(50) NOT NULL,
	staffLastname varchar(50) NOT NULL
);
CREATE TABLE LOANS (
	loanID INT PRIMARY KEY,
	costumerID INT UNIQUE NOT NULL,
	dateOfStart Date NOT NULL,
	amountNumber FLOAT NOT NULL,
	interestRate FLOAT
);

CREATE TABLE COSTUMERS (
	costumerID INT PRIMARY KEY,
	branchID INT UNIQUE,
	costumerName varchar(50) NOT NULL,
	costumerLastname varchar(50) NOT NULL,
	phoneNumber varchar(15),
	mail varchar(100)
);
CREATE TABLE EMPLOYEES (
	employeeID INT PRIMARY KEY,
	branchID INT UNIQUE,
	employeeName varchar(50) NOT NULL,
	employeeLastname varchar(50) NOT NULL,
	employeeDepartment varchar(50) NOT NULL
);
CREATE TABLE PEYMENTS (
	peymentID INT PRIMARY KEY,
	loanID INT UNIQUE,
	paymentDate Date NOT NULL,
	paymentAmount INT NOT NULL
);
CREATE TABLE BANKS (
	bankID INT PRIMARY KEY,
	bankName varchar(50) UNIQUE,
	bankFax varchar(50) UNIQUE,
	bankAdress varchar(100) NOT NULL,
	bankPhone varchar(15)
);
CREATE TABLE CARDTYPES (
	bankID INT PRIMARY KEY,
	cardType varchar(30) NOT NULL,
	CONSTRAINT FK_CARDTYPE FOREIGN KEY (bankID) REFERENCES BANKS (bankID)
);
CREATE TABLE MASTERCARDS (
	bankID INT PRIMARY KEY,
	CONSTRAINT FK_MASTERCARD FOREIGN KEY (bankID) REFERENCES BANKS (bankID)
);
CREATE TABLE VISAS (
	bankID INT PRIMARY KEY,
	CONSTRAINT FK_VISAS FOREIGN KEY (bankID) REFERENCES BANKS (bankID)
);
CREATE TABLE AMERICANEXPRESS (
	bankID INT PRIMARY KEY,
	CONSTRAINT FK_AMERÝCAN FOREIGN KEY (bankID) REFERENCES BANKS (bankID)
);

CREATE TABLE OTHERTYPES (
	bankID INT PRIMARY KEY,
	CONSTRAINT FK_OTHERS FOREIGN KEY (bankID) REFERENCES BANKS (bankID)
);